### ISSUE TITLE
Blogを投稿したユーザの名前を、ブログ上に関連づけて表示させたい

### ISSUE THREAD

**Issue by oniyana** [oniyana/DIC_thema_lesson#4]

**Comment by oniyana** [comment]
oniyanaがやります

**Comment by norotime** [comment]
@oniyana 良いですね！アサインもしましょう！

**Comment by norotime** [comment]
@oniyana プロジェクト機能を使うと、カンバン方式でタスクのTODO整理ができますよーー。
https://github.com/oniyana/DIC_thema_lesson/projects
